"""Add due_date and tags to Todo

Revision ID: 8e1d23673921
Revises: becb74dcb60d
Create Date: 2026-02-25 21:54:54.580682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1d23673921'
down_revision: Union[str, Sequence[str], None] = 'becb74dcb60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
